version: 0.2

phases:
    install:
        commands:
            # npm installation
            - npm install
            - npm install -g aws-sdk
    pre_build:
        commands:
            # Pulling the environment files from private bucket
            - echo "pre_build -> commands"
    build:
        commands:
            # Building the react app and deploying to S3 bucket, invalidating the CloudFront
            - npm run build
    post_build:
        commands:
            – aws s3 sync build/. s3://aws-crud-app/
artifacts:
    files:
        - build/.
    base-directory: 'build'
    discard-paths: no
