# https://medium.com/@jeffreyrussom/react-continuous-deployments-with-aws-codepipeline-f5034129ff0e
version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
  build:
    commands:
      - echo Build started on `date`.
      - npm run build
  post_build:
    commands:
      # This file below, since it has a unique identifier, is replaced by the new version, so we are manually deleting it before adding the react build static files
      - aws s3 rm --recursive s3://aws-crud-app/precache-manifest.*/
      # Copy contents of /build to S3.
      - aws s3 cp --recursive --acl public-read ./build s3://aws-crud-app/
      # Set the cache-control headers for service-worker.js to prevent browser caching
      - >
        aws s3 cp --acl public-read
        --cache-control="max-age=0, no-cache, no-store, must-revalidate"
        ./build/service-worker.js s3://aws-crud-app/
      # Set the cache-control headers for index.html to prevent browser caching
      - >
        aws s3 cp --acl public-read
        --cache-control="max-age=0, no-cache, no-store, must-revalidate"
        ./build/index.html s3://aws-crud-app/
      # Invalidate the CloudFront cache for index.html and service-worker.js to force CloudFront to update its edge locations with the new versions
      # - >
      #   aws cloudfront create-invalidation --distribution-id ${Distribution}
      #   --paths /index.html /service-worker.js

      # For unknown reasons this script will also build an 'aws-crud-app' folder and include the same files inside of it, so we have to delete this folder after our process is run
      - aws s3 rm --recursive s3://aws-crud-app/aws-crud-app/
artifacts:
  files:
    - '**/*'
  base-directory: build
